import type { Metadata } from "next";
import "./globals.css";
import SiteNavbar from "@/components/server/site-navbar";
import SiteFooter from "@/components/server/site-footer";
import type React from "react"
import { Inter, Poppins } from "next/font/google"
import { Analytics } from "@vercel/analytics/next"

const inter = Inter({ subsets: ["latin"] })
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.variable} font-sans antialiased`}
      >
        <SiteNavbar />
        {children}
        <SiteFooter />
        <Analytics />
      </body>
    </html>
  );
}
